/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_de_pycage_FMRXEnabler
#define DBUS_GLIB_CLIENT_WRAPPERS_de_pycage_FMRXEnabler

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
de_pycage_FMRXEnabler_request (DBusGProxy *proxy, gint* OUT_result, char ** OUT_device, GError **error)

{
  return dbus_g_proxy_call (proxy, "request", error, G_TYPE_INVALID, G_TYPE_INT, OUT_result, G_TYPE_STRING, OUT_device, G_TYPE_INVALID);
}

typedef void (*de_pycage_FMRXEnabler_request_reply) (DBusGProxy *proxy, gint OUT_result, char * OUT_device, GError *error, gpointer userdata);

static void
de_pycage_FMRXEnabler_request_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_result;
  char * OUT_device;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_result, G_TYPE_STRING, &OUT_device, G_TYPE_INVALID);
  (*(de_pycage_FMRXEnabler_request_reply)data->cb) (proxy, OUT_result, OUT_device, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
de_pycage_FMRXEnabler_request_async (DBusGProxy *proxy, de_pycage_FMRXEnabler_request_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "request", de_pycage_FMRXEnabler_request_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_de_pycage_FMRXEnabler */

G_END_DECLS
